In [1]:
import pandas as pd

df = pd.read_csv("incident_event_log.csv")

In [2]:
df.head()
df.shape
df.info()
df.describe()
df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141712 entries, 0 to 141711
Data columns (total 36 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   number                   141712 non-null  object
 1   incident_state           141712 non-null  object
 2   active                   141712 non-null  bool
 3   reassignment_count       141712 non-null  int64
 4   reopen_count             141712 non-null  int64
 5   sys_mod_count            141712 non-null  int64
 6   made_sla                 141712 non-null  bool
 7   caller_id                141712 non-null  object
 8   opened_by                141712 non-null  object
 9   opened_at                141712 non-null  object
 10  sys_created_by           141712 non-null  object
 11  sys_created_at           141712 non-null  object
 12  sys_updated_by           141712 non-null  object
 13  sys_updated_at           141712 non-null  object
 14  contact_type             141712 non-null  object
 15  location                 141712 non-null  object
 16  category                 141712 non-null  object
 17  subcategory              141712 non-null  object
 18  u_symptom                141712 non-null  object
 19  cmdb_ci                  141712 non-null  object
 20  impact                   141712 non-null  object
 21  urgency                  141712 non-null  object
 22  priority                 141712 non-null  object
 23  assignment_group         141712 non-null  object
 24  assigned_to              141712 non-null  object
 25  knowledge                141712 non-null  bool
 26  u_priority_confirmation  141712 non-null  bool
 27  notify                   141712 non-null  object
 28  problem_id               141712 non-null  object
 29  rfc                      141712 non-null  object
 30  vendor                   141712 non-null  object
 31  caused_by                141712 non-null  object
 32  closed_code              141712 non-null  object
 33  resolved_by              141712 non-null  object
 34  resolved_at              141712 non-null  object
 35  closed_at                141712 non-null  object
dtypes: bool(4), int64(3), object(29)
memory usage: 35.1+ MB

Index(['number', 'incident_state', 'active', 'reassignment_count',
       'reopen_count', 'sys_mod_count', 'made_sla', 'caller_id', 'opened_by',
       'opened_at', 'sys_created_by', 'sys_created_at', 'sys_updated_by',
       'sys_updated_at', 'contact_type', 'location', 'category', 'subcategory',
       'u_symptom', 'cmdb_ci', 'impact', 'urgency', 'priority',
       'assignment_group', 'assigned_to', 'knowledge',
       'u_priority_confirmation', 'notify', 'problem_id', 'rfc', 'vendor',
       'caused_by', 'closed_code', 'resolved_by', 'resolved_at', 'closed_at'],
      dtype='object')

In [3]:
df.isnull().sum()
df.duplicated().sum()
df["number"].nunique()

24918

In [4]:
date_columns = [
    "opened_at",
    "sys_created_at",
    "sys_updated_at",
    "resolved_at",
    "closed_at"
]

for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        format="%d/%m/%Y %H:%M",
        errors="coerce"
    )

In [5]:
numeric_columns = [
    "reassignment_count",
    "reopen_count",
    "sys_mod_count"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [6]:
categorical_columns = [
    "category",
    "subcategory",
    "assignment_group",
    "assigned_to",
    "location"
]

for col in categorical_columns:
    df[col] = df[col].fillna("Unknown")

In [7]:
df["resolution_hours"] = (
    df["resolved_at"] - df["opened_at"]
).dt.total_seconds() / 3600

In [8]:
df["closure_hours"] = (
    df["closed_at"] - df["opened_at"]
).dt.total_seconds() / 3600

In [9]:
df["resolution_days"] = df["resolution_hours"] / 24

In [10]:
(df["resolution_hours"] < 0).sum()
(df["closure_hours"] < 0).sum()
df["number"].nunique()

24918

In [11]:
df.groupby("priority")["number"].nunique()

priority
1 - Critical      352
2 - High          458
3 - Moderate    23738
4 - Low           785
Name: number, dtype: int64

In [12]:
df.groupby("category")["number"].nunique()

category
?                39
Category 10       3
Category 12       1
Category 13     129
Category 14       1
Category 15       1
Category 16       2
Category 17      89
Category 19     255
Category 2        5
Category 20    1097
Category 21       8
Category 22      56
Category 23    1120
Category 24     648
Category 25       5
Category 26    3369
Category 27       1
Category 28     574
Category 29       6
Category 3        1
Category 30       5
Category 31      19
Category 32    1579
Category 33      16
Category 34     510
Category 35     520
Category 36       1
Category 37    1161
Category 38      45
Category 4        6
Category 40     699
Category 41      36
Category 42    3757
Category 43     186
Category 44     360
Category 45     660
Category 46    2516
Category 47       7
Category 48       1
Category 49       1
Category 5       10
Category 50      24
Category 51     562
Category 52       5
Category 53    2782
Category 54      34
Category 55     113
Category 56      42
Category 57     998
Category 58       1
Category 59       7
Category 6        2
Category 61     833
Category 62       5
Category 63      12
Category 7       35
Category 8       58
Category 9     1170
Name: number, dtype: int64

In [17]:
df["sla_status"] = df["made_sla"].map({
    True: "Met SLA",
    False: "Missed SLA"
})

In [18]:
df["sla_status"] = df["made_sla"].map({
    1: "Met SLA",
    0: "Missed SLA"
})

In [19]:
df["sla_status"].value_counts()

Series([], Name: count, dtype: int64)

In [20]:
df.groupby("sla_status")["number"].nunique()

Series([], Name: number, dtype: int64)

In [14]:
df.groupby("assignment_group")["number"].nunique()

assignment_group
?           3855
Group 10     525
Group 11       1
Group 12     206
Group 13      46
            ...
Group 8        2
Group 80       9
Group 81      53
Group 82      39
Group 9      454
Name: number, Length: 79, dtype: int64

In [15]:
df.groupby("priority")["resolution_hours"].mean()

priority
1 - Critical    243.275908
2 - High        175.665657
3 - Moderate    268.133298
4 - Low         407.471736
Name: resolution_hours, dtype: float64

In [16]:
incident_level = (
    df.groupby("number")["reopen_count"]
      .max()
      .reset_index()
)

reopened_incidents = incident_level[
    incident_level["reopen_count"] > 0
]

len(reopened_incidents)

275